# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 35919798 
  contracts:
  - name: stake
    address:
    - 0xec637540aE2DA2b795aFe9427B840A827cF72f9a
    handler: src/EventHandlers.ts
    events:
    - event: AdminUnlocked(bool adminUnlocked)
    - event: AutoRenew(address indexed user, uint256 id, bool autoRenew)
    - event: DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate)
    - event: DelegateVotesChanged(address indexed delegate, uint256 previousVotes, uint256 newVotes)
    - event: EIP712DomainChanged()
    - event: Extend(address indexed user, uint256 id, uint8 numWeeks)
    - event: Initialized(uint64 version)
    - event: MaxWeeksSet(uint8 newMaxWeeks, uint8 oldMaxWeeks)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Stake(address indexed user, uint256 id, uint256 amount, uint8 numWeeks)
    - event: Withdraw(address indexed user, uint256 id, uint256 amount)
unordered_multichain_mode: true
preload_handlers: true
